
CREATE TABLE copy (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    copy_code VARCHAR(50) UNIQUE NOT NULL,
    status VARCHAR(20) NOT NULL,
    acquisition_date DATE NOT NULL,
    book_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_copy_book FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE CASCADE
);